---
abstract: 'import a magic subclass'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
  Test::Requires: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Subclass::Of
name: Subclass-Of
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  Moo: 1.002000
requires:
  Exporter::TypeTiny: 0
  List::MoreUtils: 0
  Module::Runtime: 0
  Sub::Name: 0
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Subclass-Of
  homepage: https://metacpan.org/release/Subclass-Of
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-subclass-of
version: 0.001
