---
abstract: 'import a magic subclass'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::More: 0.96
  Test::Requires: 0.06
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Subclass-Of
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Subclass::Of:
    file: lib/Subclass/Of.pm
    version: 0.003
requires:
  Exporter::Tiny: 0
  List::MoreUtils: 0
  Module::Runtime: 0
  Sub::Name: 0
  namespace::clean: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Subclass-Of/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Subclass-Of
  homepage: https://metacpan.org/release/Subclass-Of
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-subclass-of
version: 0.003
